# persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama2-pv
  labels:
    topology.kubernetes.io/region: us-east-1
    topology.kubernetes.io/zone: us-east-1a
spec:
  capacity:
    storage: 24Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0915b0e5a10f7376b    
  storageClassName: genai-gp2
  persistentVolumeReclaimPolicy: Delete  
