apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-configmap
data:
  Caddyfile: |
    :80 {
      basicauth {
        {$CADDY_USERNAME} {$CADDY_PASSWORD_HASH}
      }
      reverse_proxy localhost:11434
    }