apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: update-route53-ollama
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
